<?php

/**
 * @file
 * A basic Drupal 8 Hello World Module.
 */

/**
 * Implements hook_menu().
 */
function hello_world_menu() {
 
  $items['hello/world'] = array(
    'title' => 'Hello World',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access arguments' => array('access content'),
  );
}

/**
 * Implements hook_permission().
 */
function hello_world_permission() {
  $permissions = array(
    'administer hello world' => array(
      'title' => t('Administer Hello World module'),
      'description' => t('Change the settings for Hello World module.'),
    ),
  );
 return $permissions;
}

/**
 * Implements hook_theme().
 */
function hello_world_theme() {
  return array(
    'hello_world_primary_page' => array(
      'template' => 'hello_world_primary_page',
      'variables' => array(
        'items' => array(),
      ),
      'file' => 'hello_world.theme.inc',
    ),
  );
}

/**
 * Preprocess variables for the primary hello world page.
 *
 * @param array $variables
 *  An associative array containing:
 *  - items: Array of participant names.
 */
function template_preprocess_hello_world_primary_page(&$variables) {
  // Check if there are participants.
  // If not add a default message.
  /*if (empty($variables['items'])) {
    $variables['items'][] = t('No participants found. Please add participants.');
  }

  $variables['add_link'] = l(t('Add'), 'bingo/add');
  $variables['play_link'] = l(t('Play'), 'bingo/play');*/
  if (isset($variables['items'])) {
    $results = db_query('SELECT * from hello_world limit ' . $variables['items']);
  }
  else {
    $results = db_query('SELECT * from hello_world');
  }
  $variables['results'] = $results;

}



